---
kind: List
items:
 - apiVersion: v1
   kind: Pod
   metadata:
     name: ws
   spec:
     containers:
     - name: dev
       image: 'eclipse/che-dev:nightly'
       resources:
         limits:
           memory: 5Gi
       volumeMounts:
       - mountPath: /projects
         name: projects
       - mountPath: /home/user/.m2
         name: maven
     volumes:
     - name: projects
       persistentVolumeClaim:
         claimName: projects
     - name: maven
       persistentVolumeClaim:
          claimName: maven
 - apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: projects
   spec:
     accessModes:
      - ReadWriteOnce
     resources:
       requests:
         storage: 2Gi
 - apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: maven
   spec:
     accessModes:
      - ReadWriteOnce
     resources:
       requests:
         storage: 3Gi
